# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: spring

data:
  application.properties: |-
    TEST_STRING: "Hello Test"
    demo: "Hello Demo"
    calc.test: "Hello Calc"
    TRACING_URL: http://localhost:4317
