# name space
apiVersion: v1
kind: Namespace
metadata:
  name: spring
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: spring
  name: db-config
stringData:
  db-url: 'jdbc:postgresql://....ap-northeast-2.rds.amazonaws.com/myworkdb'
  db-username: 'mywork'
  db-password: 'myworkpassword'
