apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring
  name: greet-deployment
  labels:
    app: greet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet-deployment
  template:
    metadata:
      labels:
        app: greet-deployment
    spec:
      containers:
        - name: greet-deployment
          image: greeting
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: spring
  name: greet-service
  labels:
    app: greet-service
spec:
  type: NodePort
  ports:
    - port: 8080 # CLUSTER Service 접근 포트
      nodePort: 30081
      #targetPort: 8080
  selector:
    app: greet-deployment