apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring
  name: calc-deployment
  labels:
    app: calc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc-deployment
  template:
    metadata:
      labels:
        app: calc-deployment
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: calc-deployment
          image: ${REGISTRY_URL}/calculating:latest
          # image: calculating
          # imagePullPolicy: Never # 이미지가 로컬에 존재할 경우
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
  namespace: spring
spec:
  type: ClusterIP
  selector:
    app: calc-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
