apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring
  name: greet-deployment
  labels:
    app: greet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet-app
  template:
    metadata:
      labels:
    app: greet-app
      annotations:
        sidecar.opentelemetry.io/inject: "sidecar-for-spring" # pod 에 sidecar 삽입
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: greet-deployment
          image: ${REGISTRY_URL}/greeting:latest
          # image: greeting
          # imagePullPolicy: Never # 이미지가 로컬에 존재할 경우
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: greeting-secret
            - configMapRef:
                name: demo-config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9404
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9404
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greet-service
  namespace: spring
spec:
  type: ClusterIP
  selector:
    app: greet-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080