spring:
  application:
    name: greeting
  profiles:
    active: common,monitoring

greeting:
  message: ${GREETING_MESSAGE:hello greeting}

image:
  version: ${APPLICATION_VERSION:0.0.2}

#logging:
#  level:
#    root: debug
#management:
#  otlp:
#    metrics:
#      export:
#        url: http://localhost:4318/v1/metrics
#        aggregationTemporality: cumulative
#        step: 2s
