apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: calculating
build:
  artifacts:
    - image: mydomain.com:15000/calculating
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deployment.yaml
# scaffold run
